export const permisosRoles = {
  administrador: [
    '/',
    '/home',
    '/tablas',
    '/tablas/tablaPagos',
    '/tablas/tablaImportes',
    '/tablas/socio',
    '/tablas/historialSocios',
    '/tablas/historialACE',
    '/tablas/bancos',
    '/tablas/stopDebit',
    '/reportes',
    '/reportes/directos',
    '/reportes/indirectos',
    '/archivos',
    '/calendario',
    '/tablaSocios',
  ],
  parcial: [
    '/',
    '/home',
    '/tablas',
    '/tablas/tablaPagos',
    '/tablas/tablaImportes',
    '/tablas/socio',
    '/tablas/historialSocios',
    '/tablas/historialACE',
    '/reportes',
    '/reportes/parciales',
    '/calendario',
  ],
};
